// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLSdyG1gReoZGAd_W8jCeqZ6mMVQPHpw',
    appId: '1:993029565392:web:c3d2c31a793eaa4c2e27d5',
    messagingSenderId: '993029565392',
    projectId: 'shop-app-b21a5',
    authDomain: 'shop-app-b21a5.firebaseapp.com',
    storageBucket: 'shop-app-b21a5.appspot.com',
    measurementId: 'G-1583SFJL0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlLZpyefs4o9_4C0wvlX7Dz6pLeU4rtvw',
    appId: '1:993029565392:android:ee3ed246a716f1f12e27d5',
    messagingSenderId: '993029565392',
    projectId: 'shop-app-b21a5',
    storageBucket: 'shop-app-b21a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRoFW4jxa4WDKKX8xDNpDpHqsr7lxApQ',
    appId: '1:993029565392:ios:7476bb7ba765e9792e27d5',
    messagingSenderId: '993029565392',
    projectId: 'shop-app-b21a5',
    storageBucket: 'shop-app-b21a5.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdRoFW4jxa4WDKKX8xDNpDpHqsr7lxApQ',
    appId: '1:993029565392:ios:7476bb7ba765e9792e27d5',
    messagingSenderId: '993029565392',
    projectId: 'shop-app-b21a5',
    storageBucket: 'shop-app-b21a5.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRLSdyG1gReoZGAd_W8jCeqZ6mMVQPHpw',
    appId: '1:993029565392:web:3a1c041d6ad2ed0c2e27d5',
    messagingSenderId: '993029565392',
    projectId: 'shop-app-b21a5',
    authDomain: 'shop-app-b21a5.firebaseapp.com',
    storageBucket: 'shop-app-b21a5.appspot.com',
    measurementId: 'G-88MHYS252G',
  );

}